name: Build & publish resume

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install package
        run: yarn --frozen-lockfile
      - name: Audit dependencies
        run: yarn run audit
      - name: Lint files
        run: |
          yarn run pug-lint
          yarn run stylelint
      - name: Build resume
        run: |
          yarn run build-GR
          yarn run build-EN
      - name: Set environment for release
        if: github.event_name == 'push'
        run: |
          awk -F\" '/version/{
            print "RELEASE_TAG="$4"\nRELEASE_NAME=Release\ v"$4
          }' package.json >> $GITHUB_ENV
      - name: Publish release
        if: github.event_name == 'push'
        uses: meeDamian/github-release@2.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          tag: ${{env.RELEASE_TAG}}
          name: ${{env.RELEASE_NAME}}
          gzip: false
          files: |
            Resume-GR.pdf:build/Resume-GR.pdf
            Resume-EN.pdf:build/Resume-EN.pdf
